#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════
#  GYDS Chain — RPC Node  /  WireGuard Client Setup
#
#  Installs WireGuard and configures this node as a VPN client
#  connecting to your existing WireGuard server.
#
#  Usage:
#    sudo bash setup-wireguard.sh [options]
#
#  Options:
#    --server-pubkey KEY     Server's WireGuard public key (required)
#    --server-endpoint IP:PORT  Server endpoint, e.g. 1.2.3.4:51820 (required)
#    --client-vpn-ip IP/CIDR    This node's VPN IP, e.g. 10.8.0.2/32 (required)
#    --vpn-subnet CIDR          VPN subnet routed over tunnel (default: 10.8.0.0/24)
#    --wg-port PORT             WireGuard listen port (default: 51820)
#    --dns IP                   DNS over VPN (default: none)
#    --all-traffic              Route ALL traffic through VPN (default: VPN subnet only)
#    --status                   Show WireGuard status, then exit
#    --down                     Take wg0 down, then exit
#    --up                       Bring wg0 up, then exit
#    --show-pubkey              Print this node's public key, then exit
# ══════════════════════════════════════════════════════════════
set -euo pipefail

WG_IFACE="wg0"
WG_PORT="${WG_PORT:-51820}"
SERVER_PUBKEY="${SERVER_PUBKEY:-}"
SERVER_ENDPOINT="${SERVER_ENDPOINT:-}"
CLIENT_VPN_IP="${CLIENT_VPN_IP:-10.8.0.2/32}"
VPN_SUBNET="${VPN_SUBNET:-10.8.0.0/24}"
ALL_TRAFFIC=false
DNS_SERVER=""
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

while [[ $# -gt 0 ]]; do
  case $1 in
    --server-pubkey)   SERVER_PUBKEY="$2";   shift 2 ;;
    --server-endpoint) SERVER_ENDPOINT="$2"; shift 2 ;;
    --client-vpn-ip)   CLIENT_VPN_IP="$2";   shift 2 ;;
    --vpn-subnet)      VPN_SUBNET="$2";      shift 2 ;;
    --wg-port)         WG_PORT="$2";         shift 2 ;;
    --dns)             DNS_SERVER="$2";      shift 2 ;;
    --all-traffic)     ALL_TRAFFIC=true;     shift ;;
    --status)  wg show; exit 0 ;;
    --down)    wg-quick down "$WG_IFACE" 2>/dev/null || true; echo "wg0 down"; exit 0 ;;
    --up)      wg-quick up  "$WG_IFACE" 2>/dev/null || true; echo "wg0 up";   exit 0 ;;
    --show-pubkey)
      [[ -f /etc/wireguard/privatekey ]] && wg pubkey < /etc/wireguard/privatekey || echo "No key yet — run setup first"
      exit 0 ;;
    *) shift ;;
  esac
done

log()  { echo "[$(date '+%H:%M:%S')] $*"; }
warn() { echo "[$(date '+%H:%M:%S')] WARNING: $*" >&2; }
err()  { echo "[$(date '+%H:%M:%S')] ERROR: $*" >&2; exit 1; }

[[ $EUID -ne 0 ]] && err "Run as root: sudo bash $0"

# ── Interactive prompts if required args missing ──────────────
if [[ -z "$SERVER_PUBKEY" ]]; then
  read -rp "  WireGuard server public key: " SERVER_PUBKEY
fi
if [[ -z "$SERVER_ENDPOINT" ]]; then
  read -rp "  WireGuard server endpoint (IP:PORT, e.g. 1.2.3.4:51820): " SERVER_ENDPOINT
fi
if [[ -z "$CLIENT_VPN_IP" ]]; then
  read -rp "  This node's VPN IP (e.g. 10.8.0.2/32) [10.8.0.2/32]: " inp
  CLIENT_VPN_IP="${inp:-10.8.0.2/32}"
fi

[[ -z "$SERVER_PUBKEY"   ]] && err "Server public key required (--server-pubkey)"
[[ -z "$SERVER_ENDPOINT" ]] && err "Server endpoint required (--server-endpoint)"

# ── 1. Install WireGuard ─────────────────────────────────────
log "Installing WireGuard..."
if ! command -v wg &>/dev/null; then
  if command -v apt-get &>/dev/null; then
    apt-get update -qq
    apt-get install -y wireguard wireguard-tools resolvconf
  elif command -v dnf &>/dev/null; then
    dnf install -y wireguard-tools
  elif command -v yum &>/dev/null; then
    yum install -y epel-release
    yum install -y wireguard-tools
  else
    err "Unsupported OS. Install wireguard-tools manually."
  fi
fi
log "WireGuard version: $(wg --version)"

# ── 2. Generate key pair ─────────────────────────────────────
mkdir -p /etc/wireguard
chmod 700 /etc/wireguard

KEY_FILE="/etc/wireguard/privatekey"
PUB_FILE="/etc/wireguard/publickey"

if [[ ! -f "$KEY_FILE" ]]; then
  wg genkey | tee "$KEY_FILE" | wg pubkey > "$PUB_FILE"
  chmod 600 "$KEY_FILE"
  log "Generated new WireGuard key pair."
else
  wg pubkey < "$KEY_FILE" > "$PUB_FILE"
  log "Reusing existing WireGuard private key."
fi

PRIVATE_KEY=$(cat "$KEY_FILE")
PUBLIC_KEY=$(cat "$PUB_FILE")

# ── 3. Build AllowedIPs ──────────────────────────────────────
if $ALL_TRAFFIC; then
  ALLOWED_IPS="0.0.0.0/0, ::/0"
else
  ALLOWED_IPS="$VPN_SUBNET"
fi

# ── 4. Write wg0.conf ────────────────────────────────────────
CONF_FILE="/etc/wireguard/${WG_IFACE}.conf"
cat > "$CONF_FILE" <<WGCONF
# ── GYDS Chain RPC Node — WireGuard Client ──────────────────
# Generated by setup-wireguard.sh on $(date)
# Interface: ${WG_IFACE}
# This node's VPN IP: ${CLIENT_VPN_IP}

[Interface]
PrivateKey = ${PRIVATE_KEY}
Address    = ${CLIENT_VPN_IP}
ListenPort = ${WG_PORT}
$([ -n "$DNS_SERVER" ] && echo "DNS        = ${DNS_SERVER}" || echo "# DNS      = 10.8.0.1  # uncomment and set to your VPN DNS")

# Save on close / restore on up
PostUp   = ufw route allow in on ${WG_IFACE}
PostUp   = iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE
PostDown = ufw route delete allow in on ${WG_IFACE}
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE 2>/dev/null; true

[Peer]
# Your WireGuard server
PublicKey  = ${SERVER_PUBKEY}
Endpoint   = ${SERVER_ENDPOINT}
AllowedIPs = ${ALLOWED_IPS}

# Keep the tunnel alive (essential for nodes behind NAT)
PersistentKeepalive = 25
WGCONF

chmod 600 "$CONF_FILE"
log "Wrote ${CONF_FILE}"

# ── 5. Copy template for reference ──────────────────────────
mkdir -p "${SCRIPT_DIR}/wireguard"
sed "s|PLACEHOLDER_PRIVATE_KEY|<generated-on-server>|g" "$CONF_FILE" \
  > "${SCRIPT_DIR}/wireguard/wg0.conf.template" 2>/dev/null || true

# ── 6. Open WireGuard port in UFW ───────────────────────────
if command -v ufw &>/dev/null; then
  ufw allow "${WG_PORT}"/udp comment "WireGuard VPN"
  log "Opened UFW port ${WG_PORT}/udp for WireGuard."
fi

# ── 7. Enable + start WireGuard ─────────────────────────────
systemctl enable "wg-quick@${WG_IFACE}"
wg-quick down "${WG_IFACE}" 2>/dev/null || true
wg-quick up   "${WG_IFACE}"
sleep 2

log "WireGuard status:"
wg show

# ── 8. Summary ───────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║     GYDS RPC Node — WireGuard Client Ready           ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  This node's VPN IP : ${CLIENT_VPN_IP}"
echo "  Server endpoint    : ${SERVER_ENDPOINT}"
echo "  Routes via VPN     : ${ALLOWED_IPS}"
echo ""
echo "  ┌─ ADD THIS TO YOUR WIREGUARD SERVER CONFIG ──────────┐"
echo "  │                                                      │"
echo "  │  [Peer]                                              │"
echo "  │  # GYDS rpcnode                                      │"
echo "  │  PublicKey  = ${PUBLIC_KEY}"
echo "  │  AllowedIPs = ${CLIENT_VPN_IP}              │"
echo "  │                                                      │"
echo "  └──────────────────────────────────────────────────────┘"
echo ""
echo "  After adding the peer on your server, run:"
echo "    sudo wg set wg0 peer ${PUBLIC_KEY} allowed-ips ${CLIENT_VPN_IP}"
echo "  or reload the server config:"
echo "    sudo wg syncconf wg0 <(wg-quick strip wg0)"
echo ""
echo "  Test connectivity:"
echo "    ping \$(echo ${CLIENT_VPN_IP} | cut -d/ -f1)    # ping yourself"
echo "    ping 10.8.0.1                                   # ping server"
echo ""
echo "  Useful commands:"
echo "    sudo wg show                                    # live status"
echo "    sudo bash setup-wireguard.sh --status           # same"
echo "    sudo bash setup-wireguard.sh --down             # stop VPN"
echo "    sudo bash setup-wireguard.sh --up               # start VPN"
echo "    sudo bash setup-wireguard.sh --show-pubkey      # print pubkey"
